export const ADD_HOLIDAY = 'ADD_HOLIDAY';
export const UPDATE_HOLIDAY = 'UPDATE_HOLIDAY';
export const DELETE_HOLIDAY = 'DELETE_HOLIDAY';
export const SELECT_HOLIDAY = 'SELECT_HOLIDAY';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const CLEAR_FORM = 'CLEAR_FORM';
